### ISSUE TITLE
Exception when sending POST without Content-Length header

### ISSUE THREAD

**Issue by TacoMarco** [CoPokBl/HomeworkTrackerServer#1]
When sending a POST request lacking the Content-Length header the server throws the `ObjectDisposedException`. 

7b48503 "Fixed" this problem by catching the error when it happens. This is not a legitimate fix.

If someone sent a large amount of `POST` requests lacking the `Content-Length` header to the server, it could easily overwhelm and crash the server. 

I have made attempts to resolve the issue, but none were successful. It seems to be `C#` disposing of the memory before the request is completed, this could be because the asynchronous nature of the application. 

**Do not close this issue until fixed completely**

**Comment by CoPokBl** [comment]
After researching I have discovered that there is no good way to check if the HttpRequest has been disposed without using/programming a different library, there isn't that large an issue with try-catching the ObjectDisposedException and there is no other good way of checking if it is disposed. It is because of this that I am going to be closing this issue. The issue has been reported in mono [here](https://github.com/mono/mono/issues/10435) and no one provided a solution. I will attempt to fix it if I find a solution but it isn't high priority due to it not causing any issues.
